### ISSUE TITLE
Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'cloudToDevice' to type ICollector

### ISSUE THREAD

**Issue by IanLeatherbury** [Azure/azure-functions-iothub-extension#5]
Hey guys,

Running into the following error. Not sure what is wrong with my bindings. Running in the portal. Any ideas?

> [Error] Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.C2D2'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'cloudToDevice' to type ICollector. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

My `function.json`:

```
{
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "myEventHubMessage",
      "direction": "in",
      "path": "temp_humidity",
      "connection": "razzpi_events_IOTHUB",
      "consumerGroup": "secondconsumergroup"
    },
    {
      "type": "ioTCloudToDevice",
      "name": "cloudToDevice",
      "direction": "out",
      "connection": "razzpi_events_IOTHUB"
    }
  ],
  "disabled": false
}
```

and `run.csx`:
```
#r "Newtonsoft.Json"
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

/* Sending D2C messages to C2D */ 
public static void Run(string myEventHubMessage, ICollector<string> cloudToDevice, ICollector<string> setDeviceTwin, TraceWriter log)
{
    // myEventHubMessage = D2C message 
    log.Info($"C# Event Hub trigger function processed a message: {myEventHubMessage}");
    test
    var msgJson = JsonConvert.DeserializeObject<Dictionary<string, string>>(myEventHubMessage);

    var c2dItem = new
        {
            DeviceId = msgJson["DeviceId"],
            MessageId = msgJson["MessageId"],
            Message = "CLOUD " + msgJson["Message"] 
        };  

    var setDTItem = new
        {
            DeviceId = "receiverCarol",
            UpdateId = msgJson["MessageId"],
            Patch = new
            {
                properties = new
                {
                    desired = new
                    {
                        telemetryConfig = new
                        {
                            configId = Guid.NewGuid().ToString()
                        }
                    }
                }
            }
        };
        

    try {
        cloudToDevice.Add(JsonConvert.SerializeObject(c2dItem));
    }
    catch(Exception e) {
        log.Error("Exception caught for c2dItem method: ", e);
        log.Info("failed to add to Dave");
    }
}
```

Also, my `AzureWebJobs_ExtensionPath` app setting:
![image](https://user-images.githubusercontent.com/5083430/36918952-6d7978b0-1e10-11e8-94b8-25c0704f3b95.png)

**Comment by ElleTojaroon** [comment]
In App Setting, did you set connection string? It'd have razzpi_events_IOTHUB as key and connection string as value. You can get the connection string from the app portal.

**Comment by PKaur1** [comment]
Did you find any solution to it? I am facing the same issue. I have set up my IoT Hub connection string in app settings.

**Comment by IanLeatherbury** [comment]
I did not. I ended up just connecting directly using one of the quickstart examples from somewhere like this: https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-control-device-dotnet
